---
title: "Police Budget Map by U.S. State"
output:
  flexdashboard::flex_dashboard:
    theme: spacelab
    source_code: embed
    favicon: img/ios7-location-outline.png
runtime: shiny

---


```{r setup, include = FALSE}

## available auto themes
#  ("default", "bootstrap", "cerulean", "journal", "flatly", "readable",
# "spacelab", "united", "cosmo", "lumen", "paper", "sandstone", "simplex", or
# "yeti")


# Libraries
library(dplyr)  # tidy data manipulation
library(leaflet)  # interative mapping
library(sf) # Geospatial processing library
library(spData) # Geospatial datasets
library(ggplot2) # pie chart
library(leafpop) # svg popups


# load custom styles...tbd
# tags$head(
#   tags$link(rel = "stylesheet", type = "text/css", href = "style.css")
# )


# suppress scientific notation just in case
options(scipen=999)

# load .csv locally
# df_from_csv <- read.csv("C:/repositories/r_shiny_flex_leaflet/Police_Budget_summarized.csv")
df_from_csv <- read.csv("Police_Budget_summarized.csv")

# Load states sf spatial data
us_states <- st_transform(us_states, crs = 4326) %>% #reproject states polygon to WGS84
  left_join(df_from_csv, by = c("NAME" = "State")) %>% # join state data to csv
  select(-c(GEOID,AREA,X,REGION, total_pop_10,total_pop_15)) # remove superfluous

# Select numeric type columns for dropdown selection
cols_for_map <- subset(
  colnames(us_states[ , unlist(lapply(us_states, is.numeric), use.names = FALSE)]),
  colnames(us_states[ , unlist(lapply(us_states, is.numeric), use.names = FALSE)]) != 'geometry')
names(cols_for_map) <- c("Police Budget", "Total Budget", "Percent Police")
```

```{r reactives}
# filter master dataframe columns by user variable select / radio select
# this triggers the entire mapping panel to reload
mapFiltered  <- reactive({
  us_states[c("NAME",input$category)]
})

```


```{r plots}
# function to coerce leaflet to render same group multiple times
randGroup <- function(n = 5000) {
  a <- do.call(paste0, replicate(5, sample(LETTERS, n, TRUE), FALSE))
  paste0(a, sprintf("%04d", sample(9999, n, TRUE)), sample(LETTERS, n, TRUE))
}


humanText <- function(x){
  x <- sub("_", " ", x)
  x <- stringr::str_to_title(x)
  return(x)
}


```

Column 
-------------------------------------
    
### State Police Budget Allocation Comparative Map
    
```{r map}
renderLeaflet({

  # for sanity
  req(mapFiltered())
  
  # update labels either dollar amount or percentage amount
  labelLegend <- ifelse(input$category %in% c('Total_Budget', 'Police_Budget'),labelFormat(prefix = "$"),labelFormat(suffix = "%"))
  
  # hack to generate new paired group so popup continues to appear
  newGroupId = randGroup(1)

  # constrain map to us_states polygon layer
  bounds <- us_states %>% 
    st_bbox() %>% 
    as.character()

  # define color gradient function
  colfunc <- colorRampPalette(c("orange", "blue"))
  pal <- colorBin(palette = colfunc(5), domain = NULL, bins=quantile(us_states[[input$category]], na.rm = TRUE), 
                  na.color = "#808080",  alpha = FALSE, reverse = F)

  
  # sanity test
  if (nrow(mapFiltered()) == 0) {
    return(NULL)
  }

  # Prepare the text for tooltips
  leaflet_tooltip <- paste0(
    "<div style='color:#546474'><strong>",us_states$NAME,"</strong><br/>",
    "<strong>Total Budget: </strong>",scales::dollar(us_states$Total_Budget),"<br/>",
    "<strong>Police Budget: </strong>",scales::dollar(us_states$Police_Budget),"<br/></div>"
  ) %>%
  lapply(htmltools::HTML)
  
  # primary leaflet function
  # Loads based on a reactive mapFiltered object
  leaflet(data = mapFiltered(),
    options = leafletOptions(zoomControl = FALSE)) %>%
    clearControls() %>%
    clearShapes()%>%
    clearPopups() %>%
    addProviderTiles("Esri.WorldShadedRelief") %>% 
    addPolygons(
      fillColor = ~ pal(mapFiltered()[[input$category]]),
      stroke = FALSE,
      fillOpacity = 0.6,
      group = newGroupId,
      label = leaflet_tooltip,
      labelOptions = labelOptions( 
        style = list("font-weight" = "normal", padding = "3px 8px"), 
        textsize = "13px", 
        direction = "auto"
      ),
    ) %>%
  addLegend(
    pal = pal, 
    values = ~ mapFiltered()[[input$category]],
    opacity = 0.7, 
    title = humanText(input$category),
    labFormat = labelLegend,
    position = "bottomleft"
  ) %>%
  fitBounds(bounds[1], bounds[2], bounds[3], bounds[4])  %>%
    
  # popup area
  addPopupGraphs( # POPUP pie chart control
    lapply(us_states$NAME, 
      function(i) {

        data <- data.frame(
        group=LETTERS[1:2],
        value=c(
          round((100 - us_states[us_states$NAME == i, ]$Percent_Police),1),
          round(us_states[us_states$NAME == i, ]$Percent_Police,1)
          
          )
      )
        
      # Pie Chart Code
      # consider minicharts? https://cran.r-project.org/web/packages/leaflet.minicharts/vignettes/introduction.html
      rounded <- paste0(round(as.numeric(us_states[us_states$NAME == i, ]$Percent_Police),1),"%")
      labels <- c("",rounded)
      popupPlot <- ggplot(data, aes(x="", y=value, fill=group)) +
        geom_bar(stat="identity", width = 1, color = "white") +
        coord_polar("y", start = 45) +
        geom_text(position = position_stack(vjust = 0.5),
                  aes(
          label = labels
        ), 
        color = "white") +
        scale_fill_manual(values=c("#D3D3D3","#F15F3A")) +
        ggtitle("Annual spending per latest available \napproved budget (source)") + 
        theme(legend.position = "none",
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid  = element_blank())
      
      
    return (popupPlot)
    }), group = newGroupId)
  })

  # separately controlled from leaflet pipeline
  # controls the variable dropdown html
absolutePanel(
        draggable = FALSE, left = "1%", bottom = "18%",
        selectInput(
          "category", 
          label = "User Selection:", 
          choices = cols_for_map, 
          selected = cols_for_map[1]
        ),
        width = 245,
        style = "border-radius: 5px;padding: 6px; background: rgba(255,255,255,0.8); box-shadow: 0 0 15px rgba(0,0,0,0.2)"
    )

```